### ISSUE TITLE
Compiled crashes on Windows 10

### ISSUE THREAD

**Issue by caecos** [dgbillotte/ZeroLabModules#2]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/ADSR.cpp.o src/ADSR.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/APFilter.cpp.o src/APFilter.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/AnaLogic.cpp.o src/AnaLogic.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/AnaLogic2.cpp.o src/AnaLogic2.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/CBufferTest.cpp.o src/CBufferTest.cpp
In file included from src/CBufferTest.cpp:2:
src/CBuffer.hpp: In member function 'void CBuffer::reset()':
src/CBuffer.hpp:19:3: error: 'memset' was not declared in this scope
   19 |   memset(mBuf, 0, mBufferSize*sizeof(float));
      |   ^~~~~~
src/CBuffer.hpp:1:1: note: 'memset' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
  +++ |+#include <cstring>
    1 | //#include <stdexcept>
make: *** [C:/msys64/Rack-SDK/compile.mk:69: build/src/CBufferTest.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
https://github.com/dgbillotte/ZeroLabModules/pull/1/commits/c3f8e88de6fab8b47d3eba4f0c375353f6be7530

**Comment by dgbillotte** [comment]
Hey guys, I'm glad that this is interesting to you both, but just so you know, this is my lab/sandbox for learning this stuff and as such changes wildly on a whim. I intend to extract out some parts of it as stable pieces, but right now I'm more intrigued by reverb architectures than project organization.

Additionally, I don't have a windows box at current, so can't track down anything specific to Windows. @SteveRussell33, I'll try out your fix, which looks harmless, and as long as it doesn't break on my side I'll pull it in.

Feel free to ask about any of the code...

cheers,
Daniel

**Comment by SteveRussell33** [comment]
Hey Daniel thanks for the reply.

Yeah kind of guessed this was a sandbox of sorts seeing that some modules esentially have no panel. That's cool as I'm still learning DSP and using VCV rack to do so. 
Looked at your reverb code yesterday as I'm currently fascinated by how they work and the preference choices people make when using them in a production or sound design. I have a number as VSTs and love comparing them to see the differences.

Currently working on getting a few repo's ready for Rack2, when I have more time I'll be definetly looking at your work a bit more.

Have a good day
Steve
